

# npm run build -- ttf::mihari-iosevka

[buildPlans.mihari-iosevka]
family = "Mihari Iosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.mihari-iosevka.variants]
  inherits = "ss12"

    [buildPlans.mihari-iosevka.variants.design]
    capital-b = "more-asymmetric-interrupted-serifless"
    capital-j = "flat-hook-serifed"
    capital-k = "curly-serifless"
    capital-p = "open-serifless"
    capital-q = "detached-bend-tailed"
    capital-r = "curly-open-serifless"
    f = "tailed"
    g = "double-storey-open"
    k = "curly-serifless"
    r = "earless-corner-serifless"
    t = "bent-hook-asymmetric"
    eszet = "longs-s-lig-descending-serifless"
    lower-delta = "flat-top"
    lower-pi = "tailed"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka = "curly-serifless"
    cyrl-capital-ya = "curly-open-serifless"
    cyrl-ya = "curly-open-serifless"
    zero = "oval-slashed-split"
    one = "no-base-long-top-serif"
    two = "straight-neck"
    three = "flat-top"
    four = "semi-open-non-crossing"
    six = "open-contour"
    seven = "bend-serifed"
    nine = "open-contour"
    asterisk = "hex-low"
    paren = "large-contour"
    brace = "straight"
    guillemet = "curly"
    ampersand = "upper-open"
    dollar = "interrupted"
    percent = "rings-segmented-slash"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

  [buildPlans.mihari-iosevka.ligations]
  inherits = "dlig"
  
  [buildPlans.mihari-iosevka.metric-override]
  cap = 640

[buildPlans.mihari-iosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.mihari-iosevka.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.mihari-iosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.mihari-iosevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"